name: Download Artifacts

on:
  workflow_run:
    workflows: ["Build and Upload Artifacts"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: java-artifacts
        path: build/libs
